name: "Setup Dependencies"
description: "Installs dependencies for the project"

inputs:
  root-only:
    description: "Whether to only update the root directory"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      shell: bash
      run: pipx install poetry==2.0.0
    - name: Install Python 3.13 with Poetry Cache
      uses: actions/setup-python@v5.3.0
      with:
        python-version-file: "pyproject.toml"
        cache: "poetry"
    - name: Set up Just
      uses: extractions/setup-just@v2
    - name: Install Poetry Dependencies (Root Only)
      if: ${{ inputs.root-only == 'true' }}
      shell: bash
      run: just install-root-only
    - name: Install Poetry Dependencies
      if: ${{ inputs.root-only == 'false' }}
      shell: bash
      run: just install
