name: "GitHub Stats Analyser"
description: "Analyse GitHub and generate statistics for a user's repositories"
author: "Jack Plowman"

branding:
  color: black
  icon: code

runs:
  using: "docker"
  image: docker://ghcr.io/jackplowman/github-stats-analyser:v1.1.0
  env:
    GITHUB_ACTION: "true"

inputs:
  GITHUB_TOKEN:
    description: "The GitHub token"
    required: false
    default: ${{ github.token }}
  REPOSITORY_OWNER:
    description: "The GitHub repository owner"
    required: true
