name: "Setup Runner"
description: "Sets up the runner for the workflow"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Harden Runner
      uses: step-security/harden-runner@v2.10.1
      with:
        egress-policy: audit
    - name: Set up Just
      uses: extractions/setup-just@v2
