name: Clean Caches

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions: {}

jobs:
  clean-caches:
    name: Clean Caches
    permissions:
      contents: read
    uses: JackPlowman/reusable-workflows/.github/workflows/common-clean-caches.yml@9c45cb29b936f5d30b2d66f3ff173aa2740ec990 # v2026.03.05.01
    secrets:
      workflow_github_token: ${{ secrets.GH_TOKEN }}
