name: Code Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Run Unit Tests
        run: just unit-test

      - name: Override Coverage Source Path for SonarCloud
        run: sed -i "s/<source>\/home\/runner\/work\/github-stats-analyser\/github-stats-analyser<\/source>/<source>\/github\/workspace<\/source>/g" /home/runner/work/github-stats-analyser/github-stats-analyser/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@383f7e52eae3ab0510c3cb0e7d9d150bbaeab838 # v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  validate-schema:
    name: Validate Schema
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Run GitHub Stats Analyser
        uses: ./.github/actions/local
        with:
          REPOSITORY_OWNER: ${{ github.REPOSITORY_OWNER }}

      - name: Copy generated files to github pages folder
        run: cp repository_statistics.json test/schema_validation

      - name: Validate Schema
        run: just validate-schema

  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run GitHub Stats Analyser (pre-built image)
        uses: ./
        with:
          REPOSITORY_OWNER: ${{ github.REPOSITORY_OWNER }}

      - name: Test Output
        run: test/test_output.sh
