name: Code Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python 3.12 with Poetry Cache
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Install Poetry Dependencies
        run: just install

      - name: Run Unit Tests
        run: just unit-test

      - name: Override Coverage Source Path for SonarCloud
        run: sed -i "s/<source>\/home\/runner\/work\/github-stats-analyser\/github-stats-analyser<\/source>/<source>\/github\/workspace<\/source>/g" /home/runner/work/github-stats-analyser/github-stats-analyser/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  validate-schema:
    name: Validate Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python 3.12 with Poetry Cache
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Install Poetry Dependencies
        run: just install

      - name: Run Analyser
        env:
          repository_owner: ${{ github.repository_owner }}
        run: just run

      - name: Copy generated files to github pages folder
        run: cp -r statistics/*.json test/schema_validation

      - name: Validate Schema
        run: just validate-schema
