name: "Sync labels"

on:
  push:
    branches:
      - main
    paths:
      - .github/tool-configurations/labels.yml
  workflow_dispatch:

permissions: {}

jobs:
  configure-labels:
    name: Configure Labels
    permissions:
      contents: read
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-sync-labels.yml@9c45cb29b936f5d30b2d66f3ff173aa2740ec990 # v2026.03.05.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
