name: "Sync labels"

on:
  push:
    branches:
      - main
    paths:
      - .github/tool-configurations/labels.yml
  workflow_dispatch:

permissions: {}

jobs:
  configure-labels:
    name: Configure Labels
    permissions:
      contents: read
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-sync-labels.yml@6668fca8647a7d98f8cb9e665c32bd19d753a57b # v2026.03.07.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
